ollama_base_url: "http://localhost:11434"

llm_model: "llama3"
embedding_model: "nomic-embed-text"

pdf_dir: /home/david-rodriguez/customer_bot/data/pdfs
vector_store_dir: /home/david-rodriguez/customer_bot/data/vector_store
collection_name: john_bentley_docs_minilm

chunk_size: 1000
chunk_overlap: 200

top_k: 3
